/*
|--------------------------------------------------------------------------
| VARIABLES...
|--------------------------------------------------------------------------
*/

export let tether = { // Objeto. Representa a cerquilha...
    a1: '', a2: '', a3: '',
    b1: '', b2: '', b3: '',
    c1: '', c2: '', c3: ''
}
export let playerTurn = ''; // Vez do jogador...
export let warning = ''; // Mensagem do resultado...
export let playing = false; // Saber se o jogo ta rolando ou não...